### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by GitHubDongChen** [GitHubDongChen/ssh-connect-repo#1]
- [x] 完善connect脚本help信息
- [ ] MySQL Docker 的数据备份，Readme文档完善
- [x] Dockerfile 提供 HEALTHCHECK
- [ ] 增加connect脚本和仓库版本匹配校验
- [ ] ！！！密码入库加密处理
- [x] 当仓库中不存在登录信息时，要求用户输入密码，并保存到仓库中
